##Spring Configuration
server:
  port: 8080

spring:
  application:
    name: reputation-identity

  http:
    auth-token-header-name: apiKey
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true

cloud:
  aws:
    region:
      ##static: us-east-2   # Region where you have created the queue. In this example, we have created the queue in 'ap-south-1' region.
      static: us-east-1
      auto: true
    stack:
      auto: false
---

spring:

  profiles: dev-local

apirisk:
  secret:
    region:
    name:

server:
  port: 8094

apionpremise:
  secret:
    region:
    name:

rabbit:
  host: localhost
  port: 5672
  secret:
    region:
    name:

baseUrl:
  onPremise: https://internal-apigateway-qa.bancolombia.corp/int/testing

apikeyint:
  secret:
    region: us-east-1
    name: #{secret-name-apikey-int}#

aws:
  dynamodb:
    endpoint: http://localhost:8010
    prefix: identity-
---
spring:

  profiles: dev

apirisk:
  secret:
    region: us-east-1
    name: #{secret-name-apiRisk}#


apionpremise:
  secret:
    region: us-east-1
    name: #{secret-name-onpremise}#

rabbit:
  host: b-40ed2074-7e7a-48e7-99e1-73ab9d51b773.mq.us-east-1.amazonaws.com
  port: 5671
  secret:
    region: us-east-1
    name: #{secret-name-co.com.bancolombia.restclient.rabbit}#

baseUrl:
  onPremise: https://internal-apigateway-dev.bancolombia.corp/int/development

apikeyint:
  secret:
    region: us-east-1
    name: #{secret-name-apikey-int}#

aws:
  dynamodb:
    endpoint: https://dynamodb.us-east-1.amazonaws.com
    prefix: nu0034001-vinculacion-transversal-dev-dy-

---
spring:

  profiles: qa

apirisk:
  secret:
    region: us-east-1
    name: #{secret-name-apiRisk-qa}#

apionpremise:
  secret:
    region: us-east-1
    name: #{secret-name-onpremise-qa}#

rabbit:
  host: b-0d8d1678-f561-47b6-bcfd-39224c9ada26.mq.us-east-1.amazonaws.com
  port: 5671
  secret:
    region: us-east-1
    name: #{secret-name-co.com.bancolombia.restclient.rabbit-qa}#

baseUrl:
  onPremise: https://internal-apigateway-qa.bancolombia.corp/int/testing

apikeyint:
  secret:
    region: us-east-1
    name: #{secret-name-apikey-int-qa}#

aws:
  dynamodb:
    endpoint: https://dynamodb.us-east-1.amazonaws.com
    prefix: nu0034001-vinculacion-transversal-qa-dy-